### ISSUE TITLE
SpoonRadioButton vs []

### ISSUE THREAD

**Issue by dieterve** [spoon/library#27]
Same issue as https://github.com/Spoon/library/issues/22 but for radio buttons.

**Comment by bauffman** [comment]
Can you give an example so I can reproduce this in the tests?

**Comment by dieterve** [comment]
Same with textfields. If you send a radiobutton value as array via POST then you get PHP errors.

Example: 
     $ddmHobbies = $frm->addRadioButton('hobbie', $values);

```
// causes php error
$_POST['hobbies'][] = 'test';
```

**Comment by bauffman** [comment]
Was already fixed in spoon/form. Is now also fixed in fork cms.
