### ISSUE TITLE
Postgresql Support

### ISSUE THREAD

**Issue by chtombleson** [spoon/library#30]
The database class does not handle connecting to a postgresql database very well.

I have a patch here: https://github.com/chtombleson/library/commit/5382f5341fe9410ce189ef2a079454ec2f19a085

**Comment by bauffman** [comment]
See https://github.com/Spoon/library/commit/c3ad69de2a5626ae53aeecc0a33d7cb2f7000c8f
That should fix it. Thx for your report!
