### ISSUE TITLE
[BUG] email module may not support LIVE.COM

### ISSUE THREAD

**Issue by andrewyoung24** [spoon/library#43]
modify [bug] library/spoon/email/smtp.php [233] HTTP_HOST=>SERVER_NAME 
(HTTP_POST means address:port, and because LIVE SMTP doesn't support the address which followed by ':port', so I have to modify it into SERVER_NAME ,which will only return the address.) 

you can use TELNET to recur this bug.
(

> telnet smtp.live.com 25
> HELO google.com:80
> )

**Comment by bauffman** [comment]
Hi Andrew,

Spoon is no longer active development.
