### ISSUE TITLE
Use array_key_exists to see if... errr.... a key exists in an array.

### ISSUE THREAD

**Issue by dubgeiser** [spoon/library#5]
Piece of code to illustrate the rather dramatic problem:

```
$values = array(
    '1' => 'aaa',
    '2' => 'bbb',
    '3' => 'ccc',
);

foreach($values as $value)
{
    var_dump(isset($value['label']));
}
```

Output (oh yes):

```
bool(true)
bool(true)
bool(true)
```

This way of checking if a key exists in array is used in a lot of places.  Most of the time it is "rather" ok, but I just had a decent run for my money tracking down a bug to the guts of Spoon's multi-checkbox form element that used this.

I'll make a fix for the multi checkbox, but I think it's a more than sane idea to fix this over the whole codebase in the long term.

**Comment by dubgeiser** [comment]
Upon further investigating, the root cause of the multicheckbox issue I was having can be subscribed to the fact that the type I was using for the checkbox values was wrong...  Doing the check on that instead of blindly replacing the isset() calls (which broke the tests like a mofo) seemed to be the better approach.

I'm still convinced that using array_key_exists() instead of isset() is the better choice though, but blindly substitution of isset() would not be wise.

**Comment by dubgeiser** [comment]
Fuck yeah, the fun continues.  Apparently, when you implement ArrayAccess, the offsetExists() method does NOT get called when calling array_key_exists() on the object.  When calling isset(), it does.  _sigh_

**Comment by davelens** [comment]
I will bug you tomorrow for this, it's time this issue got closure. ^^
