### ISSUE TITLE
Access to the docs on spoon-library.com is denied

### ISSUE THREAD

**Issue by jslegers** [spoon/library#52]
When I go to [spoon-library.com](http://spoon-library.com/) and I click on `documentation`, I'm sent to [spoon-library.com/docs/1.3](http://spoon-library.com/docs/1.3/). 

Unfortunately I do not have access to this link for some reason, and I'm getting a 403 error with the following message : 

```
Forbidden

You don't have permission to access /docs/1.3/ on this server.

Apache Server at spoon-library.com Port 80
```

**Comment by tijsverkoyen** [comment]
Spoon is not maintained anymore.
